This commit will,
Add a lot of changes!!

On branch xml
Changes to be committed:
       new file:   Makefile
       new file:   TEST/Example/.vimrc
       new file:   TEST/Example/base
       new file:   TEST/Example/command.sed
       new file:   TEST/Example/job-scripts/H2O-64-16mpi
       new file:   TEST/Example/job-scripts/H2O-64-1mpi
       new file:   TEST/Example/job-scripts/H2O-64-256mpi
       new file:   TEST/Example/job-scripts/H2O-64-2mpi
       new file:   TEST/Example/job-scripts/H2O-64-32mpi
       new file:   TEST/Example/job-scripts/H2O-64-4mpi
       new file:   TEST/Example/job-scripts/H2O-64-64mpi
       new file:   TEST/Example/job-scripts/H2O-64-8mpi
       new file:   TEST/Makefile
       new file:   TEST/paraevaluar.xml
       new file:   TEST/pi.c
       new file:   TEST/pi.opt.c
       modified:   create_deb.sh
       modified:   examples/pi.c
       new file:   libparaevaluar.c
       new file:   libparaevaluar.so
       modified:   paraevaluar
       new file:   paraevaluar.addfile
       modified:   paraevaluar.eval
       modified:   paraevaluar.init
       deleted:    paraevaluar.mkscript
       new file:   paraevaluar.report
       new file:   paraevaluar.script
       modified:   paraevaluar.utils
       modified:   paraevaluar.xml

diff --git a/paraevaluar.init b/paraevaluar.init
--- a/paraevaluar.init
+++ b/paraevaluar.init
@@ -2,22 +2,22 @@
 
 source paraevaluar.utils
 
-mkdir -p .paraevaluar/job-scripts
-mkdir -p .paraevaluar/intermediate-job-scripts
+if [[ -d ${PROJECT_NAME} ]];
+then
+	if ! assert_user --default-no --text "WARNING: Project already exists. Do you want to override it? [y/N]  ";
+	then
+		echo "Aborting...";
+		exit 0;	
+	fi
+fi
 
-cat > .paraevaluar/base << EOF
-#!/bin/bash
+echo "Creating new paraevaluar project: ${PROJECT_NAME}";
 
-#SBATCH --job-name
-#SBATCH --time 
+\rm -rf   ${PROJECT_NAME} 
+\mkdir -p ${PROJECT_NAME}
+\mkdir -p ${PROJECT_NAME}/job-scripts
+\mkdir -p ${PROJECT_NAME}/files
 
-#SBATCH --nodes
-#SBATCH --ntasks
-#SBATCH --cores-per-socket
+\cat > ${PROJECT_NAME}/.vimrc << EOF
 
 EOF
-
-touch .paraevaluar/modules
-touch .paraevaluar/PROLOGUE
-touch .paraevaluar/EPILOG
-touch .paraevaluar/command
